# Generated by Django 2.2 on 2020-01-21 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kategori_barang', '0003_auto_20200119_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=30)),
                ('harga', models.IntegerField(max_length=50, null=True)),
                ('deskripsi', models.CharField(max_length=50)),
                ('gambar', models.ImageField(null=True, upload_to='produk_image/')),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('kategori_barang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kategori_barang.barang')),
            ],
        ),
    ]
