# Generated by Django 2.2 on 2020-01-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='deskripsi',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
