# Generated by Django 2.2 on 2020-01-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_auto_20200121_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
