# Generated by Django 2.2 on 2020-01-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0003_produk_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='deskripsi',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
