# Generated by Django 2.2 on 2020-01-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_auto_20200122_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.IntegerField(null=True),
        ),
    ]
