# Generated by Django 2.2 on 2020-01-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('isi', models.TextField(max_length=1000)),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
