# Generated by Django 2.2 on 2020-01-20 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kategori_artikel', '0002_auto_20200119_1154'),
        ('blog', '0002_artikel_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kategori_artikel.kategori_artikel'),
        ),
    ]
