# Generated by Django 2.2 on 2020-01-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kateg_artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=35)),
                ('tanggal_buat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
