# Generated by Django 2.2 on 2020-01-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kategori_artikel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kateg_artikel',
            new_name='kategori_artikel',
        ),
    ]
