# Generated by Django 2.2 on 2020-01-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimoni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testi',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
