# Generated by Django 2.2 on 2020-01-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimoni', '0002_testi_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='testi',
            name='tanggal_kirim',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
