# Generated by Django 2.2 on 2020-01-19 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kategori_barang', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kategori_barang',
            new_name='kat',
        ),
    ]
