# Generated by Django 2.2 on 2020-01-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kategori_barang', '0002_auto_20200119_1211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kat',
            new_name='barang',
        ),
    ]
